In [1]:
import pandas as pd 
import numpy as np
from sklearn.preprocessing import StandardScaler
#Jay Saraf 2020438

In [2]:
df = pd.read_csv("Real estate.csv")

In [3]:
df

No  X1 transaction date  X2 house age  \
0      1             2012.917          32.0   
1      2             2012.917          19.5   
2      3             2013.583          13.3   
3      4             2013.500          13.3   
4      5             2012.833           5.0   
..   ...                  ...           ...   
409  410             2013.000          13.7   
410  411             2012.667           5.6   
411  412             2013.250          18.8   
412  413             2013.000           8.1   
413  414             2013.500           6.5   

     X3 distance to the nearest MRT station  X4 number of convenience stores  \
0                                  84.87882                               10   
1                                 306.59470                                9   
2                                 561.98450                                5   
3                                 561.98450                                5   
4                                 390.56840                                5   
..                                      ...                              ...   
409                              4082.01500                                0   
410                                90.45606                                9   
411                               390.96960                                7   
412                               104.81010                                5   
413                                90.45606                                9   

     X5 latitude  X6 longitude  Y house price of unit area  
0       24.98298     121.54024                        37.9  
1       24.98034     121.53951                        42.2  
2       24.98746     121.54391                        47.3  
3       24.98746     121.54391                        54.8  
4       24.97937     121.54245                        43.1  
..           ...           ...                         ...  
409     24.94155     121.50381                        15.4  
410     24.97433     121.54310                        50.0  
411     24.97923     121.53986                        40.6  
412     24.96674     121.54067                        52.5  
413     24.97433     121.54310                        63.9  

[414 rows x 8 columns]

In [4]:
df = df.reset_index(drop=True)
df

No  X1 transaction date  X2 house age  \
0      1             2012.917          32.0   
1      2             2012.917          19.5   
2      3             2013.583          13.3   
3      4             2013.500          13.3   
4      5             2012.833           5.0   
..   ...                  ...           ...   
409  410             2013.000          13.7   
410  411             2012.667           5.6   
411  412             2013.250          18.8   
412  413             2013.000           8.1   
413  414             2013.500           6.5   

     X3 distance to the nearest MRT station  X4 number of convenience stores  \
0                                  84.87882                               10   
1                                 306.59470                                9   
2                                 561.98450                                5   
3                                 561.98450                                5   
4                                 390.56840                                5   
..                                      ...                              ...   
409                              4082.01500                                0   
410                                90.45606                                9   
411                               390.96960                                7   
412                               104.81010                                5   
413                                90.45606                                9   

     X5 latitude  X6 longitude  Y house price of unit area  
0       24.98298     121.54024                        37.9  
1       24.98034     121.53951                        42.2  
2       24.98746     121.54391                        47.3  
3       24.98746     121.54391                        54.8  
4       24.97937     121.54245                        43.1  
..           ...           ...                         ...  
409     24.94155     121.50381                        15.4  
410     24.97433     121.54310                        50.0  
411     24.97923     121.53986                        40.6  
412     24.96674     121.54067                        52.5  
413     24.97433     121.54310                        63.9  

[414 rows x 8 columns]

In [5]:
target = df['Y house price of unit area']
features = df.drop('Y house price of unit area',axis=1)
features = features.drop('No',axis=1)

In [6]:
target

0      37.9
1      42.2
2      47.3
3      54.8
4      43.1
       ... 
409    15.4
410    50.0
411    40.6
412    52.5
413    63.9
Name: Y house price of unit area, Length: 414, dtype: float64

In [7]:
features

X1 transaction date  X2 house age  \
0               2012.917          32.0   
1               2012.917          19.5   
2               2013.583          13.3   
3               2013.500          13.3   
4               2012.833           5.0   
..                   ...           ...   
409             2013.000          13.7   
410             2012.667           5.6   
411             2013.250          18.8   
412             2013.000           8.1   
413             2013.500           6.5   

     X3 distance to the nearest MRT station  X4 number of convenience stores  \
0                                  84.87882                               10   
1                                 306.59470                                9   
2                                 561.98450                                5   
3                                 561.98450                                5   
4                                 390.56840                                5   
..                                      ...                              ...   
409                              4082.01500                                0   
410                                90.45606                                9   
411                               390.96960                                7   
412                               104.81010                                5   
413                                90.45606                                9   

     X5 latitude  X6 longitude  
0       24.98298     121.54024  
1       24.98034     121.53951  
2       24.98746     121.54391  
3       24.98746     121.54391  
4       24.97937     121.54245  
..           ...           ...  
409     24.94155     121.50381  
410     24.97433     121.54310  
411     24.97923     121.53986  
412     24.96674     121.54067  
413     24.97433     121.54310  

[414 rows x 6 columns]

In [14]:
scaler = StandardScaler()
scaled_data = scaler.fit_transform(features)
print(scaled_data)

[[-0.82368321  1.25562833 -0.79249504  2.00740743  1.12542986  0.44876222]
 [-0.82368321  0.15708622 -0.61661163  1.66750286  0.91244418  0.40113894]
 [ 1.54115111 -0.38779067 -0.41401527  0.30788458  1.48686011  0.68818339]
 ...
 [ 0.35873395  0.09556786 -0.54967846  0.98769372  0.82289338  0.42397202]
 [-0.52896662 -0.84478419 -0.77668389  0.30788458 -0.18475479  0.4768143 ]
 [ 1.24643452 -0.98539758 -0.78807071  1.66750286  0.42757905  0.63534112]]


In [15]:
def fit(x, y,learning_rate,epochs):

    x, y = validate(x, y)
    weight = np.ones((x.shape[1], 1))  # inicialized predictors
    num_samples = x.shape[0]  # numbers of samples
    for i in range(epochs):
        weight =weight -  learning_rate * (1 / num_samples) * x.T.dot((x.dot(weight) - y))


    return weight

def predict(x,weight):
    
    x = np.append(np.ones((x.shape[0], 1)), x, axis=1)
    return np.dot(x, weight)

def score(x,y, weight):
    x,y = validate(x,y)
    yprime = np.dot(x, weight)
    msr = np.sqrt(np.mean((yprime - y) ** 2))
    
    return msr

def validate(x,y):

    return   np.append(np.ones((x.shape[0], 1)), x, axis=1),\
             np.array(y).reshape(y.shape[0], 1)

K fold

In [16]:
def k_fold_cross_validation(k, x, y):
    '''
        Performs K Fold Valaidation on given dataset.
        Splitting given dataset to k subsets.
    '''
    
    total_size, number_features = x.shape
    subset_size = total_size // k
    # print(subset_size)
    # print(x.shape,y.shape)
    
    # Store subsets - 
    x_subsets = []
    y_subsets = []
    
    # Splits the dataset to k subsets and stores them
    for i in range(k):
        x_slice = x[i * subset_size : min((i + 1) * (subset_size), total_size)]
        y_slice = y[i * subset_size : min((i + 1) * (subset_size), total_size)]
        
        # print(i * subset_size, min((i + 1) * (subset_size), total_size))
        x_subsets.append(x_slice)
        y_subsets.append(y_slice)
    
    # print(len(x_subsets[0]))
    # print(len(y_subsets[0]))
    
    # K Fold implemntation and calculate accuracy for each iteration and store
    rmse = []
    
    # Outer loop to select test set - 
    for i in range(k):
        x_test = x_subsets[i]
        y_test = y_subsets[i]
        x_train, y_train = np.empty((1, number_features)), np.empty((1, ))
        
        
        # Inner loop to select training set
        for j in range(k):
            if i != j:
                # print(x_train.shape, y_train.shape)
                # print(x_subsets[j].shape, y_subsets[j].shape)
                x_train = np.concatenate((x_train, x_subsets[j]), axis = 0)
                y_train = np.concatenate((y_train, y_subsets[j]), axis = 0)
        
        weights = fit(x_train,y_train,0.0000001,500)
        y_predicted = predict(x_test,weights)
        calc_score = score(x_test,y_test,weights)
        print("For fold: ", str(i), " k:", str(k))
        print("rmse: "+str(calc_score))
        rmse.append(calc_score)
        
    print("\nMean RMSE for "+ str(k)+" fold: " + str(np.mean(rmse)) + "\n")
        
for i in range(2, 6):
    k_fold_cross_validation(i, features, target)

For fold:  0  k: 2
rmse: 15.512585324937858
For fold:  1  k: 2
rmse: 16.747839178981657

Mean RMSE for 2 fold: 16.130212251959758

For fold:  0  k: 3
rmse: 17.184669577950388
For fold:  1  k: 3
rmse: 17.741064171808727
For fold:  2  k: 3
rmse: 15.397016966739214

Mean RMSE for 3 fold: 16.774250238832778

For fold:  0  k: 4
rmse: 17.072130049837924
For fold:  1  k: 4
rmse: 16.683114517086253
For fold:  2  k: 4
rmse: 17.559112310582424
For fold:  3  k: 4
rmse: 15.697927748066874

Mean RMSE for 4 fold: 16.753071156393368

For fold:  0  k: 5
rmse: 16.87014867579295
For fold:  1  k: 5
rmse: 16.80193582630882
For fold:  2  k: 5
rmse: 16.73282277788583
For fold:  3  k: 5
rmse: 17.685041819838307
For fold:  4  k: 5
rmse: 15.97151250448602

Mean RMSE for 5 fold: 16.812292320862383



In [17]:
def k_fold_cross_validation(k, X, Y):
    '''
        Performs K Fold Valaidation on given dataset.
        Split given dataset to k subsets.
        Consider each subset to be a test once and rest of the subsets as training set.
        Performs naive bayes for each such split
        Outputs : Evaluation metrics for each trained model
        Returns best accuracy obtained 
    '''
    
    total_size, number_features = X.shape
    subset_size = total_size // k
    # print(subset_size)
    # print(X.shape,Y.shape)
    
    # Store subsets - 
    X_subsets = []
    Y_subsets = []
    
    # Splits the dataset to k subsets and stores them
    for i in range(k):
        X_slice = X[i * subset_size : min((i + 1) * (subset_size), total_size)]
        Y_slice = Y[i * subset_size : min((i + 1) * (subset_size), total_size)]
        
        # print(i * subset_size, min((i + 1) * (subset_size), total_size))
        X_subsets.append(X_slice)
        Y_subsets.append(Y_slice)
    
    # print(len(X_subsets[0]))
    # print(len(Y_subsets[0]))
    
    # K Fold implemntation and calculate accuracy for each iteration and store
    rmse = []
    
    # Outer loop to select test set - 
    for i in range(k):
        X_test = X_subsets[i]
        Y_test = Y_subsets[i]
        X_train, Y_train = np.empty((1, number_features)), np.empty((1, ))
        
        
        # Inner loop to select training set
        for j in range(k):
            if i != j:
                # print(X_train.shape, Y_train.shape)
                # print(X_subsets[j].shape, Y_subsets[j].shape)
                X_train = np.concatenate((X_train, X_subsets[j]), axis = 0)
                Y_train = np.concatenate((Y_train, Y_subsets[j]), axis = 0)
        
        weights = fit(X_train,Y_train,0.0000001,500)
        y_predicted = predict(X_test,weights)
        calc_score = score(X_test,Y_test,weights)
        print("For fold: ", str(i), " k:", str(k))
        print("rmse: "+str(calc_score))
        rmse.append(calc_score)
        
    print("\nMean RMSE for "+ str(k)+" fold: " + str(np.mean(rmse)) + "\n")
        
for i in range(2, 6):
    k_fold_cross_validation(i, features, target) 

For fold:  0  k: 2
rmse: 16.81237816275409
For fold:  1  k: 2
rmse: 16.747842024629715

Mean RMSE for 2 fold: 16.780110093691903

For fold:  0  k: 3
rmse: 17.18472392721599
For fold:  1  k: 3
rmse: 17.74106417188921
For fold:  2  k: 3
rmse: 15.397016966739214

Mean RMSE for 3 fold: 16.774268355281475

For fold:  0  k: 4
rmse: 17.07213004983792
For fold:  1  k: 4
rmse: 16.683114517086253
For fold:  2  k: 4
rmse: 17.559112310582424
For fold:  3  k: 4
rmse: 15.697927748066874

Mean RMSE for 4 fold: 16.753071156393368

For fold:  0  k: 5
rmse: 16.87014867579295
For fold:  1  k: 5
rmse: 16.80193582630882
For fold:  2  k: 5
rmse: 16.73282277788583
For fold:  3  k: 5
rmse: 17.685041819838307
For fold:  4  k: 5
rmse: 15.97151250448602

Mean RMSE for 5 fold: 16.812292320862383

